server:
  port: 8072
  servlet:
    context-path: /api

logging:
  level:
    org.springframework.security: trace

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

spring:
  application:
    name: gatewayserver
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      globalcors:
#        cors-configurations:
#         ' [/**]':
#            allowed-origins: "http://localhost:3000"
#            allowed-headers: "*"
#            allowed-methods:
#              - GET,
#              - POST,
#              - PUT,
#              - DELETE


#      routes:
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/user-service/**
#          filters:
#            - TokenRelay
#
#        - id: delivery-service
#          uri: lb://DELIVERY_SERVICE
#          predicates:
#            - Path=/delivery-service/**
#          filters:
#            - TokenRelay
#
#        - id: email-service
#          uri: lb://EMAIL-SERVICE
#          predicates:
#            - Path=/email-service/**
#          filters:
#            - TokenRelay
#
#        - id: cargo-movements-service
#          uri: lb://CARGO-MOVEMENTS-SERVICE
#          predicates:
#            - Path=/cargo-movements-service/**
#          filters:
#            - TokenRelay

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:7080/realms/delivery-service/protocol/openid-connect/certs
#          issuer-uri: http://localhost:7080/realms/delivery-service

#jwt:
#  secret: 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
#  expiration: 300000


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: gatewayserver
    description: Delivery service Gateway Server Application
    version: 1.0.0
